name: gazelle_core
description: A lightweight Dart web framework for scalable and developer-friendly server-side projects.
version: 0.8.0
repository: https://github.com/intales/gazelle/tree/main/packages/gazelle_core

false_secrets:
  - /test_resources/**

environment:
  sdk: ^3.3.2

dev_dependencies:
  http: ^1.2.1
  lints: ">=2.1.0 <6.0.0"
  test: ^1.24.0
dependencies:
  gazelle_serialization: ^0.1.1
