name: gazelle
description: A CLI tool to scaffold, manage and deploy Gazelle applications.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
