name: prova
description: A new Gazelle project.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.4.1

dependencies:
  file: ^7.0.0
  gazelle_core:
    path: "../../gazelle_core"

dev_dependencies:
  lints: ">=2.1.0 <4.0.0"
  test: ^1.24.0

gazelle:
